### ISSUE TITLE
Puccinier: Conversion from v1 palette

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/toolbox#1]
To make updating ports easier, it would be beneficial to be able to convert old themes to the v2 palette.

**Comment by camblomquist** [comment]
Just spitballing here and feel free to disagree, it might be preferable to require a v1 palette to be specified as the source rather than auto-detecting it. Looking at how Puccinier detects palettes, v1 would require extra logic. Not necessarily difficult to implement, but it risks a bit of spaghetti I suppose especially if there are future version changes down the road.

**Comment by Gingeh** [comment]
@camblomquist That is a valid concern and I agree that it will have to be treated differently from other palettes. Another likely source of spaghetti is accounting for the multiple revisions to the palette between v1 and v2.

**Comment by ap-1** [comment]
Until something similar is added to this repo, people who want to convert between v1.3 and v2 can look toward [my version](https://github.com/ap-1/puccinier) of puccinier. A more complete list of changes can be found [here](https://discord.com/channels/907385605422448742/907386197855322123/1003502637515292692), but this also fixes #3.
