### ISSUE TITLE
New Tool/Puccinier: Detect non-Catppuccin colours

### ISSUE THREAD

**Issue by Gingeh** [catppuccin/toolbox#2]
To aid with creating themes, it would be useful to have a tool that detects non-Catppuccin colours.

- Show the line and line number containing the detected colours.
- Optionally suggest the closest colour in each variant?

This could either be added to puccinier, or made into a separate tool.

**Comment by nekowinston** [comment]
I'm just going through open issues at the moment, this piqued my interest;
I guess it'd be something like a `catppuccin-lint`?

The trouble is, that themes like neovim would possibly show some errors, since they [mix colours](https://github.com/catppuccin/nvim/blob/4f88948b7b5c160908b4e4e90befd45d01d96e64/lua/catppuccin/groups/editor.lua#L54-L55). And my perception is, that neovim has always been something of an authoritative repo regarding our whole style guide.
The linked example wouldn't show warnings, since two palette colours are mixed; but it might be a concern with preprocessors like `scss`.

Regarding suggestions for the closest match: In my build script for Catppuccin Blender, I'm already doing this in pure JS:
https://github.com/nekowinston/ctp-blender/blob/ee1ed891161a21f39e730de117aad9602908c85b/convert.cjs#L65-L77

I can definitely see the value of a tool like it!

**Comment by nekowinston** [comment]
Closing because of #66
